Most recent version of scripts from Bruce Blinn's website.
At http://bruceblinn.com/books/bashbook/index.html, Bruce Blinn discusses a
follow-up to his original shell script book, one that included modified versions
of his original scripts.

That book was never published, but Bruce has made the scripts from that book
available for download, again as a tar archive. This commit is the contents of
that archive.

diff --git a/bin/Cat b/bin/Cat
--- a/bin/Cat
+++ b/bin/Cat
@@ -18,20 +18,23 @@
 #		written to standard error.
 #
 ####################################################################
+CMDNAME=$(basename $0)
 ERROR=0			# Has there been an error (0=no, 1=yes)?
 LINE=			# Line read from file.
+OLD_IFS=$IFS
 
 while [ $# -gt 0 ]
 do
 	if [ ! -r "$1" ]; then
-		echo "Cannot find file $1" 1>&2
+		echo "$CMDNAME: Cannot find file $1" 1>&2
 		ERROR=1
 	else
 		IFS=
-		while read LINE
+		while read -r LINE
 		do
 			echo "$LINE"
 		done <"$1"
+		IFS=$OLD_IFS
 	fi
 	shift
 done
diff --git a/bin/findcmd b/bin/findcmd
--- a/bin/findcmd
+++ b/bin/findcmd
@@ -28,15 +28,20 @@
 #	2	Command was not found.
 #
 ####################################################################
-CMDNAME=`basename $0`
+CMDNAME=$(basename $0)
+USAGE="Usage: $CMDNAME command"
+COMMAND=		# Command being searched for.
 FOUND=FALSE		# Has the command been found?
+OLD_IFS=$IFS		# Original value of IFS variable.
+TMP_PATH=		# For parsing PATH variable.
 
 if [ $# -ne 1 ]; then
-	echo "Usage: $CMDNAME command" 1>&2
+	echo "$USAGE" 1>&2
 	exit 1
 fi
 
 COMMAND=$1
+
 case $COMMAND in
 	*/* )	if [ -x "$COMMAND" -a ! -d "$COMMAND" ]; then
 			echo "$COMMAND"
@@ -44,25 +49,30 @@ case $COMMAND in
 		fi
 		;;
 
-	* )	IFS=:
-		for dir in `echo "$PATH"	|
-			  sed -e 's/^:/.:/'	\
-		  	      -e 's/::/:.:/g'	\
-			      -e 's/:$/:./'`
+	* )	TMP_PATH=$(echo $PATH |
+				sed -e 's/^:/.:/'	\
+				    -e 's/::/:.:/g'	\
+				    -e 's/:$/:./')
+
+		IFS=:
+		set $TMP_PATH
+		IFS=$OLD_IFS
+
+		for dir
 		do
-			if [ -x "$dir/$COMMAND" -a ! \
-				-d "$dir/$COMMAND" ]
+			if [ -x "$dir/$COMMAND" -a \
+			     ! -d "$dir/$COMMAND" ]
 			then
 				echo "$dir/$COMMAND"
 				FOUND=TRUE
 				break
 			fi
-			done
-			;;
+		done
+		;;
 esac
 
 if [ "$FOUND" = "FALSE" ]; then
-	echo "$COMMAND not found"
+	echo "$COMMAND not found" 1>&2
 	exit 2
 else
 	exit 0
