Updated comments and whitespace.
Bruce Blinn made updated versions of his scripts available on his website, and
the comments in this commit were taken from those versions. Indentation in those
versions also changed, from spaces to tabs.

diff --git a/shbook/Cat b/shbook/Cat
--- a/shbook/Cat
+++ b/shbook/Cat
@@ -1,45 +1,39 @@
 #!/bin/sh
 #
-# Copyright 1995, by Hewlett-Packard Company
-#
-# The code in this file is from the book "Portable Shell
-# Programming" by Bruce Blinn, published by Prentice Hall.
-# This file may be copied free of charge for personal,
-# non-commercial use provided that this notice appears in
-# all copies of the file.  There is no warranty, either
-# expressed or implied, supplied with this code.
+# Copyright (c) 2008 by Bruce Blinn
 #
 # NAME
-#    Cat - concatinate files
+#	Cat - concatenate files
 #
 # SYNOPSIS
-#    Cat [file ...]
+#	Cat [file ...]
 #
 # DESCRIPTION
-#    This command concatinates the files by reading each
-#    file in sequence and writing it to the standard output.
+#	This command concatenates the specified files by reading
+#	each file in sequence and writing it to the standard output.
 #
 # RETURN VALUE
-#    0    Successful completion
-#    1    One or more files were not found
+#	0	Successful completion.
+#	1	One or more files were not found; see the message
+#		written to standard error.
 #
-############################################################
-ERROR=0             # Has there been an error (0=no, 1=yes)
-LINE=               # Line read from file
+####################################################################
+ERROR=0			# Has there been an error (0=no, 1=yes)?
+LINE=			# Line read from file.
 
 while [ $# -gt 0 ]
 do
-     if [ ! -r "$1" ]; then
-          echo "Cannot find file $1" 1>&2
-          ERROR=1
-     else
-          IFS=
-          while read LINE
-          do
-               echo "$LINE"
-          done <"$1"
-     fi
-     shift
+	if [ ! -r "$1" ]; then
+		echo "Cannot find file $1" 1>&2
+		ERROR=1
+	else
+		IFS=
+		while read LINE
+		do
+			echo "$LINE"
+		done <"$1"
+	fi
+	shift
 done
 
 exit $ERROR
diff --git a/shbook/DirCmp b/shbook/DirCmp
--- a/shbook/DirCmp
+++ b/shbook/DirCmp
@@ -1,56 +1,45 @@
 #!/bin/sh
 #
-# Copyright 1995, by Hewlett-Packard Company
-#
-# The code in this file is from the book "Portable Shell
-# Programming" by Bruce Blinn, published by Prentice Hall.
-# This file may be copied free of charge for personal,
-# non-commercial use provided that this notice appears in
-# all copies of the file.  There is no warranty, either
-# expressed or implied, supplied with this code.
+# Copyright (c) 2008 by Bruce Blinn
 #
 # NAME
-#    DirCmp - compare the files in two directories
+#	DirCmp - compare the files in two directories
 #
 # SYNOPSIS
-#    DirCmp [-v] [dir1] dir2
+#	DirCmp [-v] [dir1] dir2
 #
 # DESCRIPTION
-#    This command compares the files in two directories and
-#    lists the files that are not the same.  There will be
-#    three separate lists for: 
+#	This command compares the files in two directories and lists
+#	the files that are not the same.  There will be three
+#	separate lists for:
 #
-#    1. Files not in the first directory, but in the second
-#    2. Files not in the second directory, but in the first
-#    3. Files in both directories, but not the same
+#	1. Files not in the first directory, but in the second.
+#	2. Files not in the second directory, but in the first.
+#	3. Files in both directories, but not the same.
 #
-#    -v   Verbose option.  This option prints the lines that
-#         are different rather than just the name of the
-#         file when the file is in both directories, but the
-#         files are not the same.
-#
+# OPTIONS
+#	-v	Verbose.  For files that are in both directories but
+#		not the same, print the lines that are different
+#		in addition to the name of the file.
 # RETURN VALUE
-#    0    The directories are the same
-#    1    Usage error or abnormal termination
-#    2    The directories are not the same
+#	0	The directories are the same.
+#	1	Error - see the message written to standard error.
+#	2	The directories are not the same.
 #
-# CHANGES
-#    14 Jun 00  Fix type: changed "exit2" to "exit 2".
-#
-############################################################
+####################################################################
 CMDNAME=`basename $0`
 USAGE="Usage: $CMDNAME [-v] [dir1] dir2"
-VERBOSE=FALSE
-CURDIR=`pwd`                  # Current directory
-FOUND=FALSE                   # Differences found?
-FIRST=
-DIR1=                         # Source directory
-DIR2=                         # Target directory
-DIR1_FILES=/tmp/files1.$$     # Files in dir1
-DIR2_FILES=/tmp/files2.$$     # Files in dir2
-ALL_FILES=/tmp/allfiles.$$    # Files in dir1 or dir2
-COMMON_FILES=/tmp/comfiles.$$ # Files in dir1 and dir2
-TMP=/tmp/tmp.$$               # Temporary file
+VERBOSE=FALSE			# Verbose option.
+CURDIR=`pwd`			# Current directory.
+FOUND=FALSE			# Differences found?
+FIRST=				# Has header been printed?
+DIR1=				# Name of source directory.
+DIR2=				# Name of target directory.
+DIR1_FILES=/tmp/files1.$$	# List of files in dir1.
+DIR2_FILES=/tmp/files2.$$	# List of files in dir2.
+ALL_FILES=/tmp/allfiles.$$	# List of files in dir1 or dir2.
+COMMON_FILES=/tmp/comfiles.$$	# List of files in dir1 and dir2.
+TMP=/tmp/tmp.$$			# Temporary file.
 
 trap 'rm -f /tmp/*.$$; exit 1' 1 2 3 15
 
@@ -59,50 +48,50 @@ trap 'rm -f /tmp/*.$$; exit 1' 1 2 3 15
 #
 while :
 do
-     case $1 in
-          -v)  VERBOSE=TRUE
-               shift
-               ;;
-          --)  shift
-               break
-               ;;
-          -*)  echo "$USAGE" 1>&2
-               exit 1
-               ;;
-          *)   break
-               ;;
-     esac
+	case $1 in
+		-v)	VERBOSE=TRUE
+			shift
+			;;
+		--)	shift
+			break
+			;;
+		-*)	echo "$USAGE" 1>&2
+			exit 1
+			;;
+		*)	break
+			;;
+	esac
 done
 
 #
 # Get command line arguments.
 #
 if [ $# -eq 1 ]; then
-     DIR1="."
-     DIR2="$1"
+	DIR1="."
+	DIR2="$1"
 elif [ $# -eq 2 ]; then
-     DIR1="$1"
-     DIR2="$2"
+	DIR1="$1"
+	DIR2="$2"
 else
-     echo "$USAGE" 1>&2
-     exit 1
+	echo "$USAGE" 1>&2
+	exit 1
 fi
 
 #
 # Check the directories.
 #
 if [ ! -d $DIR1 ]; then
-     echo "$DIR1 is not a directory." 1>&2
-     exit 2
+	echo "$DIR1 is not a directory." 1>&2
+	exit 2
 fi
 
 if [ ! -d $DIR2 ]; then
-     echo "$DIR2 is not a directory." 1>&2
-     exit 2
+	echo "$DIR2 is not a directory." 1>&2
+	exit 2
 fi
 
 #
-# Find the files to compare.
+# Create the lists of files to compare.
 #
 cd $DIR1
 find . \( -type f -o -type l \) -print | sort >$DIR1_FILES
@@ -115,22 +104,22 @@ cd $CURDIR
 #
 # Build a list of all files.
 #
-cat $DIR1_FILES $DIR2_FILES | sort | uniq    >$ALL_FILES
-cat $DIR1_FILES $DIR2_FILES | sort | uniq -d >$COMMON_FILES
+cat $DIR1_FILES $DIR2_FILES | sort | uniq	>$ALL_FILES
+cat $DIR1_FILES $DIR2_FILES | sort | uniq -d	>$COMMON_FILES
 
 #
 # Print the files that are in dir2, but not in dir1.
 #
 cat $DIR1_FILES $ALL_FILES | sort | uniq -u >$TMP
 if [ -s $TMP ]; then
-     FOUND=TRUE
-     echo ""
-     echo "Files missing from $DIR1:"
-     for f in `cat $TMP`
-     do
-          f=`expr $f : '..\(.*\)'`
-          echo "	$f"
-     done
+	FOUND=TRUE
+	echo ""
+	echo "Files missing from $DIR1:"
+	for f in `cat $TMP`
+	do
+		f=`expr $f : '..\(.*\)'`
+		echo "	$f"
+	done
 fi
 
 #
@@ -138,14 +127,14 @@ fi
 #
 cat $DIR2_FILES $ALL_FILES | sort | uniq -u >$TMP
 if [ -s $TMP ]; then
-     FOUND=TRUE
-     echo ""
-     echo "Files missing from $DIR2:"
-     for f in `cat $TMP`
-     do
-          f=`expr $f : '..\(.*\)'`
-          echo "	$f"
-     done
+	FOUND=TRUE
+	echo ""
+	echo "Files missing from $DIR2:"
+	for f in `cat $TMP`
+	do
+		f=`expr $f : '..\(.*\)'`
+		echo "	$f"
+	done
 fi
 
 #
@@ -155,30 +144,30 @@ fi
 FIRST=TRUE
 for f in `cat $COMMON_FILES`
 do
-     cmp -s $DIR1/$f $DIR2/$f
-     if [ $? -ne 0 ]; then
-          FOUND=TRUE
-          f=`expr $f : '..\(.*\)'`
-          if [ "$FIRST" = "TRUE" ]; then
-               FIRST=FALSE
-               echo ""
-               echo "Files that are not the same:"
-          fi
+	cmp -s $DIR1/$f $DIR2/$f
+	if [ $? -ne 0 ]; then
+		FOUND=TRUE
+		f=`expr $f : '..\(.*\)'`
+		if [ "$FIRST" = "TRUE" ]; then
+			FIRST=FALSE
+			echo ""
+			echo "Files that are not the same:"
+		fi
 
-          if [ "$VERBOSE" = "TRUE" ]; then
-               echo ""
-               echo "File: $f"
-               diff $DIR1/$f $DIR2/$f
-          else
-               echo "	$f"
-          fi
-     fi
+		if [ "$VERBOSE" = "TRUE" ]; then
+			echo ""
+			echo "File: $f"
+			diff $DIR1/$f $DIR2/$f
+		else
+			echo "	$f"
+		fi
+	fi
 done
 
 rm -f /tmp/*.$$
 if [ $FOUND = TRUE ]; then
-     exit 2
+	exit 2
 else
-     echo "The directories are the same."
-     exit 0
+	echo "The directories are the same."
+	exit 0
 fi
diff --git a/shbook/Kill b/shbook/Kill
--- a/shbook/Kill
+++ b/shbook/Kill
@@ -1,58 +1,56 @@
 #!/bin/sh
 #
-# Copyright 1995, by Hewlett-Packard Company
-#
-# The code in this file is from the book "Portable Shell
-# Programming" by Bruce Blinn, published by Prentice Hall.
-# This file may be copied free of charge for personal,
-# non-commercial use provided that this notice appears in
-# all copies of the file.  There is no warranty, either
-# expressed or implied, supplied with this code.
+# Copyright (c) 2008 by Bruce Blinn
 #
 # NAME
-#    Kill - kill a process (send a signal) by name
+#	Kill - kill a process (send a signal) by name
 #
 # SYNOPSIS
-#    Kill [-signal] ProcessName
+#	Kill [-signal | -s signal] processName
 #
 # DESCRIPTION
-#    This command will send a signal to any process with the
-#    name ProcessName.  The user will be asked for
-#    conformation before sending the signal to the process.
+#	This command will send a signal to any process with the
+#	specified name.  For each process that is found, the user
+#	will be asked for confirmation before sending the signal to
+#	the process.
 #
-#    -signal
-#         Specifies the signal to send to the process.  Any
-#         value that is accepted by the kill(1) command may
-#         be specified.  For example, either -9 or -KILL can
-#         be used to send signal nine to the process.  If
-#         this option is not used, signal 15 (TERM) will be
-#         sent to the process.
+# OPTIONS
+#	-signal or -s signal
+#		This option specifies the signal to send to the
+#		process(es).  Either the signal number or the signal
+#		name may be used.  For example:
+#
+#			Kill -s 9 processName
+#			Kill -s SIGKILL processName
+#			Kill -9 processName
+#			Kill -SIGKILL processName
+#
+#		If this option is not specified, SIGTERM will be
+#		sent to the process(es).
 #
 # RETURN VALUE
-#    0    Successful completion
-#    1    Usage error or abnormal termination
+#	0	Successful completion.  It is not an error if the
+#		process is not found.
 #
-# CHANGES
-#    26 May 00  Updated for Linux.
-#    30 Oct 00  Added w option to ps command for Linux.
+#	1	Error - see the message written to standard error.
 #
-############################################################
+####################################################################
 CMDNAME=`basename $0`
 USAGE="Usage: $CMDNAME [-signal] ProcessName"
-SIGNAL=                  # Optional signal; see kill(1)
-NAME=                    # Name of process to kill
-PID=                     # PID of process being checked
-OWNER=                   # Owner of process being checked
+SIGNAL=			# Signal option for the kill(1) command.
+NAME=			# Name of process to kill.
+PID=			# PID of process being checked.
+OWNER=			# Owner of process being checked.
 PATH=$PATH:`dirname $0`
-OLD_IFS=$IFS             # Original value of IFS variable
-PROCNAME=                # Name of process being checked
-PS_OPTS=                 # Options for ps command
+OLD_IFS=$IFS		# Original value of IFS variable
+PROCNAME=		# Name of process being checked
+PS_OPTS=		# Options for ps command
 PROCESS_LIST=/tmp/list.$$ # Output of ps command
-TITLE_PRINTED=FALSE      # Title printed? (TRUE or FALSE)
-FOUND=FALSE              # Found matching process?
-LINE=                    # Single line of output from ps
-COL=                     # Column where process name begins
-SYSTEM=`SystemType`      # String identifying the system
+TITLE_PRINTED=FALSE	# Title printed? (TRUE or FALSE)
+FOUND=FALSE		# Found matching process?
+LINE=			# Single line of output from ps
+COL=			# Column where process name begins
+SYSTEM=`SystemType`	# String identifying the system
 
 . SystemType.sh
 . GetYesNo.sh
@@ -63,15 +61,15 @@ trap 'rm -f /tmp/*.$$; exit 1' 1 2 3 15
 # Get and check the command line parameters.
 #
 case $1 in
-     --)  shift
-          ;;
-     -*)  SIGNAL=$1      # Leave the hyphen
-          shift
-          ;;
+	--)	shift
+		;;
+	-*)	SIGNAL=$1	 # Leave the hyphen
+		shift
+		;;
 esac
 if [ $# -ne 1 ]; then
-     echo "$USAGE" 1>&2
-     exit 1
+	echo "$USAGE" 1>&2
+	exit 1
 fi
 
 NAME=$1        # Get the name of the process to kill.
@@ -80,19 +78,19 @@ NAME=$1        # Get the name of the process to kill.
 # Determine which options to use with the ps command.
 #
 case $SYSTEM in
-     SUNBSD | ULTRIX ) PS_OPTS="-auxw"     ;;
-     * )               PS_OPTS="-efw"      ;;
+	SUNBSD | ULTRIX )	PS_OPTS="-auxw"	;;
+	* )			PS_OPTS="-efw"	;;
 esac
 
 #
 # Get a list of the current processes and filter out the
 # lines that do not contain the process we are looking for.
 #
-ps $PS_OPTS                   |
-     sed '1d'                 |    # Remove the title line
-     grep "$NAME"             |    # Eliminate the chaff
-     grep -v "$0"             |    # Eliminate this process
-     grep -v "ps $PS_OPTS"    >$PROCESS_LIST
+ps $PS_OPTS			|
+	sed '1d'		|	# Remove the title line
+	grep "$NAME"		|	# Eliminate the chaff
+	grep -v "$0"		|	# Eliminate this process
+	grep -v "ps $PS_OPTS"	>$PROCESS_LIST
 
 #
 # Check each process.
@@ -101,59 +99,59 @@ exec <$PROCESS_LIST
 IFS=
 while read LINE
 do
-     IFS=$OLD_IFS
-     #
-     # Get the owner, PID, and name of the process.
-     #
-     set $LINE
-     OWNER=$1
-     PID=$2
+	IFS=$OLD_IFS
+	#
+	# Get the owner, PID, and name of the process.
+	#
+	set $LINE
+	OWNER=$1
+	PID=$2
 
-     #
-     # Determine the column where the process name begins.
-     #
-     case $SYSTEM in
-          LINUX )                       COL=49 ;;
-          AIX | HP | SGI | SOLARIS )    COL=48 ;;
-          SUNBSD | DECOSF )             COL=57 ;;
-          ULTRIX )                      COL=51 ;;
-          * )  echo "Unexpected system type." 1>&2
-               exit 1
-               ;;
-     esac
+	#
+	# Determine the column where the process name begins.
+	#
+	case $SYSTEM in
+		LINUX )				COL=49 ;;
+		AIX | HP | SGI | SOLARIS )	COL=48 ;;
+		SUNBSD | DECOSF )		COL=57 ;;
+		ULTRIX )			COL=51 ;;
+		* )	echo "Unexpected system type." 1>&2
+			exit 1
+			;;
+	esac
 
-     LINE=`echo "$LINE" | cut -c$COL-`
-     set dummy $LINE
-     shift
-     PROCNAME=$1
+	LINE=`echo "$LINE" | cut -c$COL-`
+	set dummy $LINE
+	shift
+	PROCNAME=$1
 
-     if [ "$PROCNAME" = "$NAME" -o \
-          "`basename $PROCNAME`" = "$NAME" ]; then
+	if [ "$PROCNAME" = "$NAME" -o \
+		"`basename $PROCNAME`" = "$NAME" ]; then
 
-          FOUND=TRUE
+		FOUND=TRUE
 
-          #
-          # Print title.
-          #
-          if [ "$TITLE_PRINTED" = "FALSE" ]; then
-               echo "PID	Owner	Process"
-               TITLE_PRINTED=TRUE
-          fi
+		#
+		# Print title.
+		#
+		if [ "$TITLE_PRINTED" = "FALSE" ]; then
+			echo "PID	Owner	Process"
+			TITLE_PRINTED=TRUE
+		fi
 
-          #
-          # Ask user.
-          #
-          if GetYesNo \
-               "$PID	$OWNER	$PROCNAME (y/n)? " </dev/tty
-          then
-               kill $SIGNAL $PID
-          fi
-     fi
-     IFS=
+		#
+		# Ask user.
+		#
+		if GetYesNo \
+			"$PID	$OWNER	$PROCNAME (y/n)? " </dev/tty
+		then
+			kill $SIGNAL $PID
+		fi
+	fi
+	IFS=
 done
 
 if [ "$FOUND" = "FALSE" ]; then
-     echo "Process \"$NAME\" not found."
+	echo "Process \"$NAME\" not found."
 fi
 
 rm -f /tmp/*.$$
diff --git a/shbook/findcmd b/shbook/findcmd
--- a/shbook/findcmd
+++ b/shbook/findcmd
@@ -1,77 +1,69 @@
 #!/bin/sh
 #
-# Copyright 1995, by Hewlett-Packard Company
-#
-# The code in this file is from the book "Portable Shell
-# Programming" by Bruce Blinn, published by Prentice Hall.
-# This file may be copied free of charge for personal,
-# non-commercial use provided that this notice appears in
-# all copies of the file.  There is no warranty, either
-# expressed or implied, supplied with this code.
+# Copyright (c) 2008 by Bruce Blinn
 #
 # NAME
-#    findcmd - search for a command
+#	findcmd - search for a command
 #
 # SYNOPSIS
-#    findcmd command
+#	findcmd command
 #
 # DESCRIPTION
-#    This command searches the directories listed in the
-#    PATH variable for the command.  It makes a reasonable
-#    attempt to find the same command as would be found by
-#    the shell, except that it does not find functions or
-#    built-in commands:
+#	This command will search the directories listed in the PATH
+#	variable for the command.  It makes a reasonable attempt to
+#	find the same command as would be found by the shell, except
+#	that it does not find functions or built-in commands:
 #
-#    1. If the command name contains a /, the PATH variable
-#       is not used.
-#    2. The directories in the PATH variable are searched in
-#       order, from left to right.
-#    3. Files without execute access are ignored even if the
-#       file name matches the command name.
-#    4. The search concludes when the first match is found.
+#	1. If the command name contains a /, the PATH variable is
+#	   not used.
+#	2. The directories in the PATH variable are searched in
+#	   order from left to right.
+#	3. Files without execute access are ignored even if the file
+#	   name matches the command name.
+#	4. The search concludes when the first match is found.
 #
 # RETURN VALUE
-#    0    Command was found
-#    1    Usage error
-#    2    Command was not found
+#	0	Command was found.
+#	1	Error - see the message written to standard error.
+#	2	Command was not found.
 #
-############################################################
+####################################################################
 CMDNAME=`basename $0`
-FOUND=FALSE
+FOUND=FALSE		# Has the command been found?
 
 if [ $# -ne 1 ]; then
-     echo "Usage: $CMDNAME command" 1>&2
-     exit 1
+	echo "Usage: $CMDNAME command" 1>&2
+	exit 1
 fi
 
 COMMAND=$1
 case $COMMAND in
-     */* )     if [ -x "$COMMAND" -a ! -d "$COMMAND" ]; then
-                    echo "$COMMAND"
-                    FOUND=TRUE
-               fi
-               ;;
+	*/* )	if [ -x "$COMMAND" -a ! -d "$COMMAND" ]; then
+			echo "$COMMAND"
+			FOUND=TRUE
+		fi
+		;;
 
-     * )       IFS=:
-               for dir in `echo "$PATH"           |
-                           sed -e 's/^:/.:/'      \
-                               -e 's/::/:.:/g'    \
-                               -e 's/:$/:./'`
-               do
-                    if [ -x "$dir/$COMMAND" -a ! \
-                         -d "$dir/$COMMAND" ]
-                    then
-                         echo "$dir/$COMMAND"
-                         FOUND=TRUE
-                         break
-                    fi
-               done
-               ;;
+	* )	IFS=:
+		for dir in `echo "$PATH"	|
+			  sed -e 's/^:/.:/'	\
+		  	      -e 's/::/:.:/g'	\
+			      -e 's/:$/:./'`
+		do
+			if [ -x "$dir/$COMMAND" -a ! \
+				-d "$dir/$COMMAND" ]
+			then
+				echo "$dir/$COMMAND"
+				FOUND=TRUE
+				break
+			fi
+			done
+			;;
 esac
 
 if [ "$FOUND" = "FALSE" ]; then
-     echo "$COMMAND not found"
-     exit 2
+	echo "$COMMAND not found"
+	exit 2
 else
-     exit 0
+	exit 0
 fi
